package nixla

import nixla.cst.*

@main def demo(): Unit =

  // ============================================================
  // 1. Build a flake with the green builders, serialize with Pretty
  // ============================================================
  import Build as B

  val flake = B.attrs(
    B.binding(Seq("description"), B.str("A Scala dev shell, generated by nixla")),
    B.binding(Seq("inputs", "nixpkgs", "url"), B.str("github:NixOS/nixpkgs/nixpkgs-unstable")),
    B.binding(
      Seq("outputs"),
      B.patternLambda(
        Seq("self" -> None, "nixpkgs" -> None), ellipsis = false, bound = None,
        B.letIn(
          Seq(
            B.binding(Seq("pkgs"), B.select(B.ident("nixpkgs"), "legacyPackages", "x86_64-linux")),
            B.binding(Seq("jdk"), B.select(B.ident("pkgs"), "jdk21"))
          ),
          B.attrs(
            B.binding(
              Seq("devShells", "x86_64-linux", "default"),
              B.app(
                B.select(B.ident("pkgs"), "mkShell"),
                B.attrs(
                  B.binding(Seq("packages"),
                    B.list(B.select(B.ident("pkgs"), "mill"), B.ident("jdk"))),
                  B.binding(Seq("shellHook"),
                    B.strParts("echo JDK is ", B.select(B.ident("jdk"), "version")))
                )
              )
            )
          )
        )
      )
    )
  )

  println("═══ 1. built with nixla.cst.Build, serialized by Pretty ═══")
  print(Pretty(flake))

  // ============================================================
  // 2. Parse real Nix, rewrite surgically, re-emit LOSSLESSLY —
  //    comments and formatting survive; only the values change.
  // ============================================================
  val source = """# GNU hello, pinned
{ stdenv, fetchurl }:

stdenv.mkDerivation rec {
  pname = "hello";        # the classic
  version = "2.12.1";
  doCheck = true;
}
"""

  val parsed = Parser.parseGreen(source)
  assert(parsed.text == source, "lossless invariant violated!")

  val bumped = Rewrite(parsed) {
    case b if b.kind == SyntaxKind.N_BINDING && bindingName(b).contains("version") =>
      replaceValue(b, Build.str("2.13.0"))
    case b if b.kind == SyntaxKind.N_BINDING && bindingName(b).contains("doCheck") =>
      replaceValue(b, Build.bool(false))
  }

  println()
  println("═══ 2. parsed → surgical rewrite → lossless re-emit ═══")
  print(bumped.text)

  println()
  println("═══ 3. only the changed values differ; every comment survives ═══")

private def bindingName(b: GreenNode): Option[String] =
  b.children.collectFirst {
    case n: GreenNode if n.kind == SyntaxKind.N_ATTRPATH => n.text
  }

private def replaceValue(b: GreenNode, value: GreenNode): GreenNode =
  GreenNode(b.kind, b.children.map {
    case n: GreenNode if n.kind != SyntaxKind.N_ATTRPATH => value
    case other                                           => other
  })
